services:
nginx:
container_name: nginx
build:
context: ./requirements/nginx
dockerfile: Dockerfile
image: nginx:inception
depends_on:
- wordpress
ports:
- "443:443"
volumes:
- wp_data:/var/www/html:ro
- certs:/etc/nginx/certs
environment:
- DOMAIN_NAME=${DOMAIN_NAME}
- COUNTRY=${COUNTRY}
- STATE=${STATE}
- CITY=${CITY}
- ORG=${ORG}
networks:
- inception
restart: always


wordpress:
container_name: wordpress
build:
context: ./requirements/wordpress
dockerfile: Dockerfile
image: wordpress:inception
depends_on:
- mariadb
volumes:
- wp_data:/var/www/html
environment:
- MYSQL_DATABASE=${MYSQL_DATABASE}
- MYSQL_USER=${MYSQL_USER}
- MYSQL_HOST=${MYSQL_HOST}
- WP_TITLE=${WP_TITLE}
- WP_URL=${WP_URL}
- WP_ADMIN_USER=${WP_ADMIN_USER}
- WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
secrets:
- db_password
- wp_admin_password
networks:
- inception
restart: always


mariadb:
container_name: mariadb
build:
context: ./requirements/mariadb
dockerfile: Dockerfile
image: mariadb:inception
volumes:
- db_data:/var/lib/mysql
environment:
- MYSQL_DATABASE=${MYSQL_DATABASE}
- MYSQL_USER=${MYSQL_USER}
secrets:
- db_password
- db_root_password
networks:
- inception
restart: always


networks:
inception:
name: inception


volumes:
db_data:
driver: local
driver_opts:
type: none
o: bind
file: ../secrets/credentials.txt